export const REQUEST_SEND_EMAIL = 'REQUEST_SEND_EMAIL'
export const SUCCESS_SEND_EMAIL = 'SUCCESS_SEND_EMAIL'
export const FAILURE_SEND_EMAIL = 'FAILURE_SEND_EMAIL'

export const REQUEST_ADD_CONTACT = 'REQUEST_ADD_CONTACT'
export const SUCCESS_ADD_CONTACT = 'SUCCESS_ADD_CONTACT'
export const FAILURE_ADD_CONTACT = 'FAILURE_ADD_CONTACT'

export const REQUEST_ADD_CONTACT_TO_GOOGLE_SHEET =
  'REQUEST_ADD_CONTACT_TO_GOOGLE_SHEET'
export const SUCCESS_ADD_CONTACT_TO_GOOGLE_SHEET =
  'SUCCESS_ADD_CONTACT_TO_GOOGLE_SHEET'
export const FAILURE_ADD_CONTACT_TO_GOOGLE_SHEET =
  'FAILURE_ADD_CONTACT_TO_GOOGLE_SHEET'

export const CLEAR_ALL_DATA = 'CLEAR_ALL_DATA'

export const ADD_MESSAGE_SUCCESS_ERROR_SUCCESS =
  'ADD_MESSAGE_SUCCESS_ERROR_SUCCESS'
export const ADD_MESSAGE_SUCCESS_ERROR_ERROR = 'ADD_MESSAGE_SUCCESS_ERROR_ERROR'
export const CLEAR_MESSAGE_SUCCESS_ERROR = 'CLEAR_MESSAGE_SUCCESS_ERROR'

export const SET_URL = 'SET_URL'
