export const mediumBlue = '#001DFF'
export const black = '#000000'
export const summerSky = '#2796D1'
export const white = '#FFFFFF'
export const sapphire = '#020A31'
export const whiteSmoke = '#EDEAEA'
export const prussianBlue = '#001E57'
export const persianBlue = '#171DB2'

export const gainsboro = '#E4E4E4'
